credentials:
  usernames:
    will:
      email: wpennell48@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: William Pennell
      password: abc # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
pre-authorized:
  emails:
    -
